---
# Ensure ELK target directory exists
- name: Ensure ELK directory exists
  ansible.builtin.file:
    path: "{{ elk_compose_dir }}"
    state: directory
    mode: "0755"
  tags:
    - elk-setup

# Copy full ELK directory (configs, Dockerfiles, extensions, setup)
- name: Copy ELK directory
  ansible.posix.synchronize:
    src: files/elk/
    dest: "{{ elk_compose_dir }}/"
    recursive: yes
    perms: yes
    owner: yes
    group: yes
    archive: yes
  tags:
    - elk-setup

- name: Deploy Kibana configuration from template
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: "{{ elk_compose_dir }}/kibana/config/kibana.yml"
    mode: '0644'
    owner: root
    group: root
  tags:
    - elk-setup

# Copy environment file (templated)
- name: Copy environment file
  ansible.builtin.template:
    src: templates/.env.j2
    dest: "{{ elk_compose_dir }}/.env"
    mode: "0600"
  tags:
    - elk-setup

# Run ELK setup service
- name: Run ELK setup
  community.docker.docker_compose_v2:
    project_src: "{{ elk_compose_dir }}"
    services:
      - setup
    profiles:
      - setup
    state: present
    recreate: always
    wait: yes
  tags:
    - elk-setup

# Start all ELK services
- name: Start all ELK services
  community.docker.docker_compose_v2:
    project_src: "{{ elk_compose_dir }}"
    state: present
    recreate: auto
    wait: yes
  tags:
    - elk-main
