---
# tasks/main.yml

- name: Install dependencies
  become: true
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - jq
    state: present

- name: Add Docker GPG key
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  args:
    creates: /etc/apt/trusted.gpg.d/docker.asc

- name: Add Docker repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Docker
  become: true
  apt:
    name: docker-ce
    state: present

- name: Get latest Docker Compose version
  shell: curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name
  register: compose_version
  changed_when: false

- name: Install Docker Compose
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version.stdout }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Start and enable Docker service
  become: true
  service:
    name: docker
    state: started
    enabled: yes

- name: Verify Docker installation
  command: docker --version
  register: docker_version
  changed_when: false

- name: Verify Docker Compose installation
  command: docker-compose --version
  register: docker_compose_version
  changed_when: false

- name: Ensure docker proxy config directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy Docker proxy configuration
  ansible.builtin.template:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart docker

- name: Reload systemd daemon (if config changed)
  ansible.builtin.systemd:
    daemon_reload: yes
  when: ansible_facts.services is defined and 'docker.service' in ansible_facts.services
  notify: restart docker

- name: Create Docker data directory on /home
  become: true
  file:
    path: /home/docker
    state: directory
    owner: root
    group: root
    mode: '0710'
  notify: restart docker

- name: Configure Docker to use /home/docker as data-root
  become: true
  copy:
    content: |
      {
        "data-root": "/home/docker"
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: restart docker

- name: Ensure Docker service is started and enabled
  become: true
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes
  notify: restart docker

- name: Print Docker version
  debug:
    var: docker_version.stdout

- name: Print Docker Compose version
  debug:
    var: docker_compose_version.stdout
